Repository owncloud/ocis-accounts, pull requests merged in 2020-07, with the labels that each got.

#52 [Tests-Only] Add tests infrastructure and tests for ocis-accounts
  .drone.star
  Makefile
  nightwatch.conf.js
  package.json
  ui/tests/acceptance/features/accounts.feature
  ui/tests/acceptance/pageobjects/accountsPage.js
  ui/tests/acceptance/stepDefinitions/accountsContext.js
  ui/tests/config/drone/identifier-registration.yml
  ui/tests/config/drone/ocis-config.json
  ui/tests/config/drone/proxy-config.json
  ui/tests/run-acceptance-test.sh
  yarn.lock
Labels: QA-team

#50 initial group api implementation
  Makefile
  go.mod
  go.sum
  pkg/proto/v0/accounts.pb.go
  pkg/proto/v0/accounts.pb.micro.go
  pkg/proto/v0/accounts.pb.web.go
  pkg/proto/v0/accounts.proto
  pkg/proto/v0/accounts.swagger.json
  pkg/proto/v0/bleve.go
  pkg/server/grpc/server.go
  pkg/service/v0/accounts.go
  pkg/service/v0/groups.go
  pkg/service/v0/service.go
  pkg/service/v0/settings.go
  ui/components/accounts/AccountsList.vue
  ui/store/index.js
Labels: enhancement

#60 Fix the account and group id mismatch in delete group method
  changelog/unreleased/fix-account-group-id.md
  pkg/service/v0/groups.go
Labels: bug

#32 [Tests-Only] Add tests for gRPC
  .gitignore
  go.mod
  go.sum
  pkg/proto/v0/accounts.pb.micro_test.go
Labels: QA-team

#64 Use alpine:latest instead of alpine:edge in docker builds
  changelog/unreleased/use-alpine-latest.md
  docker/Dockerfile.linux.amd64
  docker/Dockerfile.linux.arm
  docker/Dockerfile.linux.arm64
Labels: bug

#65 fix password related segfaults
  changelog/unreleased/fix-segfault.md
  changelog/unreleased/tighten-screws.md
  pkg/proto/v0/accounts.pb.micro_test.go
  pkg/service/v0/accounts.go
Labels: bug

#68 fix int parsing
  changelog/unreleased/fix-int-queries.md
  pkg/provider/bleve.go
Labels: bug

#71 Add write mutexes
  changelog/unreleased/add-write-mutexes.md
  pkg/service/v0/accounts.go
  pkg/service/v0/groups.go
Labels: bug

#74 fix index mapping
  changelog/unreleased/fix-index-mapping.md
  pkg/provider/bleve.go
  pkg/service/v0/accounts.go
  pkg/service/v0/groups.go
  pkg/service/v0/service.go
Labels: bug
